name: Trigger Vercel Deploy Hook

on:
  push:
    branches:
      - main

jobs:
  vercel-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deploy hook
        run: |
          curl -X POST "https://api.vercel.com/v1/integrations/deploy/prj_lK66xZOAHO1Oa3UMGqU6YNkwHXTO/vaV4akQAE6?target=production"
